-- V1: Create all tables for Al-Quran web application

CREATE TABLE mst_language (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(10)  NOT NULL UNIQUE,
    name        VARCHAR(100) NOT NULL,
    native_name VARCHAR(100),
    is_active   BOOLEAN DEFAULT TRUE,
    created_at  TIMESTAMP
);

CREATE TABLE mst_surah (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surah_number     INT          NOT NULL UNIQUE,
    name_arabic      VARCHAR(100) NOT NULL,
    name_latin       VARCHAR(100) NOT NULL,
    name_translation VARCHAR(200),
    total_ayahs      INT          NOT NULL,
    revelation_type  VARCHAR(20)  NOT NULL,
    revelation_order INT,
    description      TEXT,
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP
);

CREATE TABLE mst_ayah (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surah_id      BIGINT  NOT NULL REFERENCES mst_surah(id),
    ayah_number   INT     NOT NULL,
    text_arabic   TEXT    NOT NULL,
    text_simple   TEXT,
    juz_number    INT,
    hizb_number   INT,
    manzil_number INT,
    page_number   INT,
    sajda         BOOLEAN DEFAULT FALSE,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    UNIQUE (surah_id, ayah_number)
);
CREATE INDEX idx_juz  ON mst_ayah(juz_number);
CREATE INDEX idx_page ON mst_ayah(page_number);

CREATE TABLE mst_translation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ayah_id         BIGINT NOT NULL REFERENCES mst_ayah(id),
    language_id     BIGINT NOT NULL REFERENCES mst_language(id),
    translator_name VARCHAR(200),
    text            TEXT,
    footnotes       TEXT,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    UNIQUE (ayah_id, language_id)
);
CREATE INDEX idx_translation_language ON mst_translation(language_id);

CREATE TABLE mst_word (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ayah_id          BIGINT NOT NULL REFERENCES mst_ayah(id),
    position         INT    NOT NULL,
    text_arabic      TEXT   NOT NULL,
    text_simple      VARCHAR(200),
    transliteration  VARCHAR(200),
    root_word        VARCHAR(100),
    grammar_notes    TEXT,
    created_at       TIMESTAMP
);
CREATE INDEX idx_ayah_position ON mst_word(ayah_id, position);

CREATE TABLE mst_word_translation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id     BIGINT NOT NULL REFERENCES mst_word(id),
    language_id BIGINT NOT NULL REFERENCES mst_language(id),
    translation TEXT   NOT NULL,
    created_at  TIMESTAMP,
    UNIQUE (word_id, language_id)
);

CREATE TABLE mst_tafsir_source (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    author      VARCHAR(200),
    language_id BIGINT NOT NULL REFERENCES mst_language(id),
    description TEXT,
    is_active   BOOLEAN DEFAULT TRUE,
    created_at  TIMESTAMP
);

CREATE TABLE mst_tafsir (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ayah_id          BIGINT NOT NULL REFERENCES mst_ayah(id),
    tafsir_source_id BIGINT REFERENCES mst_tafsir_source(id),
    text             TEXT,
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP,
    UNIQUE (ayah_id, tafsir_source_id)
);

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL UNIQUE,
    email         VARCHAR(200) NOT NULL UNIQUE,
    password_hash VARCHAR(300) NOT NULL,
    full_name     VARCHAR(200),
    is_active     BOOLEAN DEFAULT TRUE,
    last_login    TIMESTAMP,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP
);

CREATE TABLE user_bookmark (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    ayah_id    BIGINT NOT NULL REFERENCES mst_ayah(id),
    notes      TEXT,
    created_at TIMESTAMP,
    UNIQUE (user_id, ayah_id)
);
