-- V3: Seed all 114 surahs

INSERT INTO mst_surah (surah_number, name_arabic, name_latin, name_translation,
                       total_ayahs, revelation_type, revelation_order,
                       description, created_at, updated_at)
VALUES
(1, 'سُورَةُ ٱلْفَاتِحَةِ', 'Al-Faatiha', 'The Opening', 7, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(2, 'سُورَةُ البَقَرَةِ', 'Al-Baqara', 'The Cow', 286, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(3, 'سُورَةُ آلِ عِمۡرَانَ', 'Aal-i-Imraan', 'The Family of Imraan', 200, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(4, 'سُورَةُ النِّسَاءِ', 'An-Nisaa', 'The Women', 176, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(5, 'سُورَةُ المَائـِدَةِ', 'Al-Maaida', 'The Table', 120, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(6, 'سُورَةُ الأَنۡعَامِ', 'Al-An''aam', 'The Cattle', 165, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(7, 'سُورَةُ الأَعۡرَافِ', 'Al-A''raaf', 'The Heights', 206, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(8, 'سُورَةُ الأَنفَالِ', 'Al-Anfaal', 'The Spoils of War', 75, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(9, 'سُورَةُ التَّوۡبَةِ', 'At-Tawba', 'The Repentance', 129, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(10, 'سُورَةُ يُونُسَ', 'Yunus', 'Jonas', 109, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(11, 'سُورَةُ هُودٍ', 'Hud', 'Hud', 123, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(12, 'سُورَةُ يُوسُفَ', 'Yusuf', 'Joseph', 111, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(13, 'سُورَةُ الرَّعۡدِ', 'Ar-Ra''d', 'The Thunder', 43, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(14, 'سُورَةُ إِبۡرَاهِيمَ', 'Ibrahim', 'Abraham', 52, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(15, 'سُورَةُ الحِجۡرِ', 'Al-Hijr', 'The Rock', 99, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(16, 'سُورَةُ النَّحۡلِ', 'An-Nahl', 'The Bee', 128, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(17, 'سُورَةُ الإِسۡرَاءِ', 'Al-Israa', 'The Night Journey', 111, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(18, 'سُورَةُ الكَهۡفِ', 'Al-Kahf', 'The Cave', 110, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(19, 'سُورَةُ مَرۡيَمَ', 'Maryam', 'Mary', 98, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(20, 'سُورَةُ طه', 'Taa-Haa', 'Taa-Haa', 135, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(21, 'سُورَةُ الأَنبِيَاءِ', 'Al-Anbiyaa', 'The Prophets', 112, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(22, 'سُورَةُ الحَجِّ', 'Al-Hajj', 'The Pilgrimage', 78, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(23, 'سُورَةُ المُؤۡمِنُونَ', 'Al-Muminoon', 'The Believers', 118, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(24, 'سُورَةُ النُّورِ', 'An-Noor', 'The Light', 64, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(25, 'سُورَةُ الفُرۡقَانِ', 'Al-Furqaan', 'The Criterion', 77, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(26, 'سُورَةُ الشُّعَرَاءِ', 'Ash-Shu''araa', 'The Poets', 227, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(27, 'سُورَةُ النَّمۡلِ', 'An-Naml', 'The Ant', 93, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(28, 'سُورَةُ القَصَصِ', 'Al-Qasas', 'The Stories', 88, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(29, 'سُورَةُ العَنكَبُوتِ', 'Al-Ankaboot', 'The Spider', 69, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(30, 'سُورَةُ الرُّومِ', 'Ar-Room', 'The Romans', 60, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(31, 'سُورَةُ لُقۡمَانَ', 'Luqman', 'Luqman', 34, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(32, 'سُورَةُ السَّجۡدَةِ', 'As-Sajda', 'The Prostration', 30, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(33, 'سُورَةُ الأَحۡزَابِ', 'Al-Ahzaab', 'The Clans', 73, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(34, 'سُورَةُ سَبَإٍ', 'Saba', 'Sheba', 54, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(35, 'سُورَةُ فَاطِرٍ', 'Faatir', 'The Originator', 45, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(36, 'سُورَةُ يسٓ', 'Yaseen', 'Yaseen', 83, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(37, 'سُورَةُ الصَّافَّاتِ', 'As-Saaffaat', 'Those drawn up in Ranks', 182, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(38, 'سُورَةُ صٓ', 'Saad', 'The letter Saad', 88, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(39, 'سُورَةُ الزُّمَرِ', 'Az-Zumar', 'The Groups', 75, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(40, 'سُورَةُ غَافِرٍ', 'Ghafir', 'The Forgiver', 85, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(41, 'سُورَةُ فُصِّلَتۡ', 'Fussilat', 'Explained in detail', 54, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(42, 'سُورَةُ الشُّورَىٰ', 'Ash-Shura', 'Consultation', 53, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(43, 'سُورَةُ الزُّخۡرُفِ', 'Az-Zukhruf', 'Ornaments of gold', 89, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(44, 'سُورَةُ الدُّخَانِ', 'Ad-Dukhaan', 'The Smoke', 59, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(45, 'سُورَةُ الجَاثِيَةِ', 'Al-Jaathiya', 'Crouching', 37, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(46, 'سُورَةُ الأَحۡقَافِ', 'Al-Ahqaf', 'The Dunes', 35, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(47, 'سُورَةُ مُحَمَّدٍ', 'Muhammad', 'Muhammad', 38, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(48, 'سُورَةُ الفَتۡحِ', 'Al-Fath', 'The Victory', 29, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(49, 'سُورَةُ الحُجُرَاتِ', 'Al-Hujuraat', 'The Inner Apartments', 18, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(50, 'سُورَةُ قٓ', 'Qaaf', 'The letter Qaaf', 45, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(51, 'سُورَةُ الذَّارِيَاتِ', 'Adh-Dhaariyat', 'The Winnowing Winds', 60, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(52, 'سُورَةُ الطُّورِ', 'At-Tur', 'The Mount', 49, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(53, 'سُورَةُ النَّجۡمِ', 'An-Najm', 'The Star', 62, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(54, 'سُورَةُ القَمَرِ', 'Al-Qamar', 'The Moon', 55, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(55, 'سُورَةُ الرَّحۡمَٰن', 'Ar-Rahmaan', 'The Beneficent', 78, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(56, 'سُورَةُ الوَاقِعَةِ', 'Al-Waaqia', 'The Inevitable', 96, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(57, 'سُورَةُ الحَدِيدِ', 'Al-Hadid', 'The Iron', 29, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(58, 'سُورَةُ المُجَادلَةِ', 'Al-Mujaadila', 'The Pleading Woman', 22, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(59, 'سُورَةُ الحَشۡرِ', 'Al-Hashr', 'The Exile', 24, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(60, 'سُورَةُ المُمۡتَحنَةِ', 'Al-Mumtahana', 'She that is to be examined', 13, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(61, 'سُورَةُ الصَّفِّ', 'As-Saff', 'The Ranks', 14, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(62, 'سُورَةُ الجُمُعَةِ', 'Al-Jumu''a', 'Friday', 11, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(63, 'سُورَةُ المُنَافِقُونَ', 'Al-Munaafiqoon', 'The Hypocrites', 11, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(64, 'سُورَةُ التَّغَابُنِ', 'At-Taghaabun', 'Mutual Disillusion', 18, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(65, 'سُورَةُ الطَّلَاقِ', 'At-Talaaq', 'Divorce', 12, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(66, 'سُورَةُ التَّحۡرِيمِ', 'At-Tahrim', 'The Prohibition', 12, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(67, 'سُورَةُ المُلۡكِ', 'Al-Mulk', 'The Sovereignty', 30, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(68, 'سُورَةُ القَلَمِ', 'Al-Qalam', 'The Pen', 52, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(69, 'سُورَةُ الحَاقَّةِ', 'Al-Haaqqa', 'The Reality', 52, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(70, 'سُورَةُ المَعَارِجِ', 'Al-Ma''aarij', 'The Ascending Stairways', 44, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(71, 'سُورَةُ نُوحٍ', 'Nooh', 'Noah', 28, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(72, 'سُورَةُ الجِنِّ', 'Al-Jinn', 'The Jinn', 28, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(73, 'سُورَةُ المُزَّمِّلِ', 'Al-Muzzammil', 'The Enshrouded One', 20, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(74, 'سُورَةُ المُدَّثِّرِ', 'Al-Muddaththir', 'The Cloaked One', 56, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(75, 'سُورَةُ القِيَامَةِ', 'Al-Qiyaama', 'The Resurrection', 40, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(76, 'سُورَةُ الإِنسَانِ', 'Al-Insaan', 'Man', 31, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(77, 'سُورَةُ المُرۡسَلَاتِ', 'Al-Mursalaat', 'The Emissaries', 50, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(78, 'سُورَةُ النَّبَإِ', 'An-Naba', 'The Announcement', 40, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(79, 'سُورَةُ النَّازِعَاتِ', 'An-Naazi''aat', 'Those who drag forth', 46, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(80, 'سُورَةُ عَبَسَ', 'Abasa', 'He frowned', 42, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(81, 'سُورَةُ التَّكۡوِيرِ', 'At-Takwir', 'The Overthrowing', 29, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(82, 'سُورَةُ الانفِطَارِ', 'Al-Infitaar', 'The Cleaving', 19, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(83, 'سُورَةُ المُطَفِّفِينَ', 'Al-Mutaffifin', 'Defrauding', 36, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(84, 'سُورَةُ الانشِقَاقِ', 'Al-Inshiqaaq', 'The Splitting Open', 25, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(85, 'سُورَةُ البُرُوجِ', 'Al-Burooj', 'The Constellations', 22, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(86, 'سُورَةُ الطَّارِقِ', 'At-Taariq', 'The Morning Star', 17, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(87, 'سُورَةُ الأَعۡلَىٰ', 'Al-A''laa', 'The Most High', 19, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(88, 'سُورَةُ الغَاشِيَةِ', 'Al-Ghaashiya', 'The Overwhelming', 26, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(89, 'سُورَةُ الفَجۡرِ', 'Al-Fajr', 'The Dawn', 30, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(90, 'سُورَةُ البَلَدِ', 'Al-Balad', 'The City', 20, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(91, 'سُورَةُ الشَّمۡسِ', 'Ash-Shams', 'The Sun', 15, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(92, 'سُورَةُ اللَّيۡلِ', 'Al-Lail', 'The Night', 21, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(93, 'سُورَةُ الضُّحَىٰ', 'Ad-Dhuhaa', 'The Morning Hours', 11, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(94, 'سُورَةُ الشَّرۡحِ', 'Ash-Sharh', 'The Consolation', 8, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(95, 'سُورَةُ التِّينِ', 'At-Tin', 'The Fig', 8, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(96, 'سُورَةُ العَلَقِ', 'Al-Alaq', 'The Clot', 19, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(97, 'سُورَةُ القَدۡرِ', 'Al-Qadr', 'The Power, Fate', 5, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(98, 'سُورَةُ البَيِّنَةِ', 'Al-Bayyina', 'The Evidence', 8, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(99, 'سُورَةُ الزَّلۡزَلَةِ', 'Az-Zalzala', 'The Earthquake', 8, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(100, 'سُورَةُ العَادِيَاتِ', 'Al-Aadiyaat', 'The Chargers', 11, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(101, 'سُورَةُ القَارِعَةِ', 'Al-Qaari''a', 'The Calamity', 11, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(102, 'سُورَةُ التَّكَاثُرِ', 'At-Takaathur', 'Competition', 8, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(103, 'سُورَةُ العَصۡرِ', 'Al-Asr', 'The Declining Day, Epoch', 3, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(104, 'سُورَةُ الهُمَزَةِ', 'Al-Humaza', 'The Traducer', 9, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(105, 'سُورَةُ الفِيلِ', 'Al-Fil', 'The Elephant', 5, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(106, 'سُورَةُ قُرَيۡشٍ', 'Quraish', 'Quraysh', 4, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(107, 'سُورَةُ المَاعُونِ', 'Al-Maa''un', 'Almsgiving', 7, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(108, 'سُورَةُ الكَوۡثَرِ', 'Al-Kawthar', 'Abundance', 3, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(109, 'سُورَةُ الكَافِرُونَ', 'Al-Kaafiroon', 'The Disbelievers', 6, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(110, 'سُورَةُ النَّصۡرِ', 'An-Nasr', 'Divine Support', 3, 'MADANIYAH', NULL, NULL, NOW(), NOW()),
(111, 'سُورَةُ المَسَدِ', 'Al-Masad', 'The Palm Fibre', 5, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(112, 'سُورَةُ الإِخۡلَاصِ', 'Al-Ikhlaas', 'Sincerity', 4, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(113, 'سُورَةُ الفَلَقِ', 'Al-Falaq', 'The Dawn', 5, 'MAKKIYAH', NULL, NULL, NOW(), NOW()),
(114, 'سُورَةُ النَّاسِ', 'An-Naas', 'Mankind', 6, 'MAKKIYAH', NULL, NULL, NOW(), NOW());
